version: '3.9'
services:      
  java_db:
    container_name: "java_db"
    image: mysql:8.0.33
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Db152
      - MYSQL_DATABASE=biblioteca
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    volumes:
      - java_db_data:/var/lib/mysql
      
  biblioteca:
    build: .
    container_name: "biblioteca_app"
    image: "biblioteca_v1" 
    ports:
      - 9090:9090
    links:
      - java_db
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/biblioteca?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=1234
    depends_on:
      - java_db
      
volumes:
  java_db_data:

