version: '3.9'
services:
  biblioteca:
    build: .
    container_name: "biblioteca_app"
    image: "biblioteca_v1" 
    ports:
      - 9090:9090    
    environment:
      - DATABASE_URL=jdbc:sqlserver://integracionbook.database.windows.net:1433;database=biblioteca;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - DATABASE_USERNAME=desarrolladorbook
      - DATABASE_PASSWORD=Book12345
    
      
volumes:
  java_db_data:

